[project]
name = "agent_backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "langchain>=1.2.10",
    "langchain-google-genai>=4.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",   
    "W",   
    "F",   
    "I",   
    "B",  
    "UP",  
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

